name: cenideth_login
description: este programa es para iniciar sesion con hotmail

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  firebase_core: ^1.20.0
  firebase_auth: ^3.5.0
  flutter_auth_buttons: ^0.10.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_sign_in: ^5.4.0

flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/imagenes/

